esp32:
  board: lolin32_lite
  framework:
    type: esp-idf
  
esphome:
  name: blinklolin
  on_boot:
    priority: -100
    then:
      - logger.log: 'Lolin boot triggered'
      - switch.turn_on: LEDint
  on_shutdown:
    priority: -100
    then:
      - switch.turn_off: LEDint
      - logger.log: "Lolin shutdown triggered"


  
# Enable logging
logger:

wifi:
  networks:
  - ssid: !secret GKssid
    password: !secret GKpassword
  - ssid: !secret BGssid
    password: !secret BGpassword
  - ssid: !secret SSssid
    password: !secret SSpassword
  ap:
    ssid: !secret FBssid
    password: !secret FBpassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:


ota:
  - platform: esphome


esp32_touch:
  setup_mode: false  
  low_voltage_reference: 0.5V  # One of 0.5V, 0.6V, 0.7V, 0.8V. Default is 0.5V.
  high_voltage_reference: 2.7V    # One of 2.4V, 2.5V, 2.6V, 2.7V. Default is 2.7V.
  voltage_attenuation: 0V    # One of 1.5V, 1V, 0.5V, 0V. Default is 0V.

output:
  - platform: gpio
    pin: GPIO22
    id: 'GPLEDint'

switch:
  - platform: output
    id: LEDint
    name: "LEDint"
    output: "GPLEDint"
    inverted: true
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: esp32_touch
    name: "esp32touchpad"
    id: "esp32touchpad"
    pin: GPIO14
    threshold: 350


interval:
  - interval: 1s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - switch.toggle: LEDint
  - interval: 2s
    then:
      - if:
          condition:
            wifi.connected:
          else:
            - switch.toggle: LEDint
  
  
