esp32:
  board: lolin32_lite
  framework:
    type: esp-idf
  
esphome:
  name: presencekld7
  on_boot:
    priority: -100.0
    then:
      - logger.log: 'PMon boot triggered'
      - switch.turn_on: LEDint
  on_shutdown:
    priority: -100.0
    then:
      - switch.turn_off: LEDint
      - logger.log: "PMon shutdown triggered"


# Enable logging
logger:

wifi:
  networks:
  - ssid: !secret GKssid
    password: !secret GKpassword
  - ssid: !secret BGssid
    password: !secret BGpassword
  - ssid: !secret SSssid
    password: !secret SSpassword
  ap:
    ssid: !secret FBssid
    password: !secret FBpassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:


ota:
  - platform: esphome

# Enable Home Assistant API
#
# Achtung: Für Offlinekalender muss der API-Reboot auf 0s gesetzt werden, da die Tonne sonst alle 15 Minuten neu startet.
#
api:
  reboot_timeout: 60min  # only enable this when creating an offline device; 0s=never reboot


  
time:
  - platform: homeassistant

sun:
  latitude: 51.14°
  longitude: 9.414°

globals:
  - id: last_valid_abs_speed
    type: float
    restore_value: no
    initial_value: '0.0'

external_components:
- source: components
#    github://HolliDolli/esphome-component-kld7@MyMod
  components: [ kld7 ]
#- source: components
#  components: [ kld6 ]

uart:
  - id: uart_bus
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 115200
    parity: EVEN
#  debug:
#    direction: BOTH
#    dummy_receiver: true
 
#  - id: radar_uart
#    tx_pin: GPIO17
#    rx_pin: GPIO16
#    baud_rate: 115200
#    parity: EVEN

#kld6:
#  uart_id: radar_uart
#  presence_timeout: 3s
 
 
kld7:
  uart_id: uart_bus
  invert_angle: true

  
one_wire:
  - platform: gpio
    pin: GPIO19

output:
  - platform: gpio
    pin: GPIO22
    id: 'GPLEDint'

switch:
  - platform: output
    id: "LEDint"
    name: "LEDint"
    output: "GPLEDint"
    inverted: true
    restore_mode: ALWAYS_ON
  
text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: kld7
    name: K-LD7
    raw_json:
      name: Raw JSON
    json:
      internal: true
      name: JSON
     
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
  - platform: dallas_temp
#    address: 0x7d592f7f0e64ff28 brauchen wir nicht mehr. gibt ja jetzt index :-)
    index: 0
    name: temp1
    update_interval: 30s
  - platform: kld7
    name: K-LD7 Sensor
    speed:
      name: Speed
    avg_speed:
      name: Avg speed
    points:
      name: Points
    raw_speed:
      name: Raw speed
      id: raw_speed
      on_value:
        then:
          - component.update: absolute_speed
    raw_angle:
      name: Raw angle
      id: raw_angle
    raw_distance:
      name: Raw distance
    raw_magnitude:
      name: Raw magnitude
      
      
  - platform: template
    name: "Absolute Geschwindigkeit"
    id: absolute_speed
    unit_of_measurement: "km/h"
    accuracy_decimals: 2
    device_class: "speed"
    state_class: "measurement"
    update_interval: never 
    lambda: |-
      if (id(raw_speed).has_state() && id(raw_angle).has_state()) {
        float v_raw = id(raw_speed).state;
        float angle_deg = id(raw_angle).state;
        
        float angle_rad = angle_deg * (M_PI / 180.0);
        float sin_val = fabsf(sin(angle_rad));

        // Nur wenn die Messung physikalisch sinnvoll ist (Winkel > 5°)
        // UND das Fahrzeug sich bewegt (v_raw != 0)
        if (sin_val > 0.087 && fabsf(v_raw) > 0.1) { 
          id(last_valid_abs_speed) = fabsf(v_raw / sin_val);
        }
      }
      
      // Gib immer den letzten gespeicherten Wert zurück, 
      // anstatt NAN oder 0 bei ungültigen Messpunkten.
      return id(last_valid_abs_speed);      
      
binary_sensor:
  - platform: status
    name: "Statussensor"
    id: statussensor
  - platform: kld7
    name: K-LD7
    detection:
      name: Detection
    raw_detection:
      name: Raw Detection
    raw_direction_away_from_sensor:
      name: Raw direction away from sensor
    filtered_detection:
      name: Filtered detection
      min_distance: 0
      max_distance: 800
      min_angle: -90
      max_angle: 90
      min_points: 5
      timeout: 1000

  - platform: gpio
    pin:
      number: GPIO27
      mode:
        input: true
        pulldown: true
    name: pdetect
    id: pdetect
    device_class: "motion"

  - platform: gpio
    pin:
      number: GPIO26
      mode:
        input: true
        pulldown: true
    name: pdirect
    id: pdirect

  - platform: gpio
    pin:
      number: GPIO25
      mode:
        input: true
        pulldown: true
    name: pangle

  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pulldown: true
    name: prange
    


